version: '3.9'

services:
  postgres_service:
    container_name: pg_s
    image: postgres:14.9-alpine3.17 
    hostname: postgres
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PORSGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web_riddles_service:
    container_name: w_r_s
    build:
      context: .
    ports: 
      - "80:8000"
    volumes:
      - .:/w_r_s

volumes:
  postgres_data:


